### ISSUE TITLE
use buttons

### ISSUE THREAD

**Issue by Shashank3736** [npc203/npc-cogs#38]
In help embed, if we enable the button then it should remove other buttons when adding left and right arrow buttons.

For e.g if I type !help it sends a help message with a button once I choose general for example it adds arrows but does not remove the previous buttons.

**Comment by Shashank3736** [comment]
To move to other categories we have a home button. We can click on that and go back to home. But for those who have 10 categories, more buttons only create a hassle.

**Comment by Shashank3736** [comment]
> yeah as @the-krak3n mentioned, there's that option to disable all buttons together except the navigation arrows.
> 
> > To move to other categories we have a home button. We can click on that and go back to home. But for those who have 10 categories, more buttons only create a hassle.
> 
> Well if the buttons disappeared after clicking a category and then you go back home, do you want the buttons to pop up again? if yes, that's highly ratelimit spammy (meaning discord won't be happy with it).

That makes sense too. What I want is something that exists in auttaja bot. If I go back home after I select a category then the arrows still stay there and if I click the arrow then it says interaction error. Which is a no go. So having buttons which remove when you select an option is not a bad idea. Having that thing as a config option will allow bot owners to choose what they wish for. Unlike reactions, buttons do not have a bad rate limit.

**Comment by npc203** [comment]
this is/was fixed, all buttons pop up and vanish as and when needed
