### ISSUE TITLE
[Feature Request] Category view permissions based on roles

### ISSUE THREAD

**Issue by cr0cdev** [npc203/npc-cogs#54]
Hi!

A cool extra feature would be if we could hide categories from different roles. For example if I have a Mod category then I can add permissions to Moderator role to see that category, but the normal member of the discord server does not see it.

FYI: Permissions cog does not help with this. User can not see any commands under the category, but he can see the category itself.

Thank you!

**Comment by npc203** [comment]
PRs welcome for anyone reading this.

The "don't show a category if the user doesn't have permissions to execute any of the commands under the category" will be a thing when red starts to support buttons officially.

**Comment by npc203** [comment]
_I think_, this was fixed at some point
Last time I checked the category disappears if the user cannot run any command in it
