### ISSUE TITLE
[Issue] CustomHelp on dpy2

### ISSUE THREAD

**Issue by leetfin** [npc203/npc-cogs#71]
When attempting to set a category up with chelp edit, this happens:
```
mapping values are not allowed here
  in "<unicode string>", line 2, column 7:
    - desc: Fun commands
          ^
```
This is on the dpy2 branch.
Thanks!

**Comment by npc203** [comment]
A bit late but probably an issue with your yaml, which got handled internally, check it with a yaml syntax checker online. Or I'd need more info on the command arguments which was passed
