### ISSUE TITLE
[google] `[p]google rev` doesnt work

### ISSUE THREAD

**Issue by sravan1946** [npc203/npc-cogs#72]
https://sentry.io/share/issue/317183eec8b34c03a5d983f54ed6c7de/

**Comment by npc203** [comment]
seems like google removed it's old searchbyimage feature and replaced it with google lens search, I could try a complete rewrite to scrape google lens, but it'd depend on if people are willing to use the command.

**Comment by BenCos17** [comment]
I'd defn be interested in that command tbh

**Comment by npc203** [comment]
yeah turns out we did completely rewrite to scrape google lens, [p]google rev should work in the latest update
